name: flutter_chat_types
description: >
  Utility library for the flutter_chat_ui and flutter_firebase_chat_core libraries
  which contains shared type declarations.
version: 3.6.2
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_types

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: '>=1.8.0 <2.0.0'

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
